### ISSUE TITLE
[cli] Registry for cli

### ISSUE THREAD

**Issue by techsavvyash** [SamagraX-Stencil/stencil-cli#1]
## Is there an existing issue that is already proposing this?

- [x] I have searched the existing issues

## Description

Add a registry in the stencil cli to track what all things that a particular user is using.

**Comment by Savio629** [comment]
@techsavvyash 
Any idea on how to represent to the users?
Like maybe add a command to check installed modules (maybe `stencil ls`)?

**Comment by techsavvyash** [comment]
`stencil ls` might be a good way to do it, alterantively just running `stencil` give the user a list of all available commands in a tabular format, what we can do is add another column with a flag representing whether the user is using it or not. Alterantively keeping in mind the future vision for the product we would want a dotfile like `.stencil` or a config file `stencil.config.json` to be generated which lists what modules a project is using and also to update it once the user adds/removes some feature using the CLI.
