### ISSUE TITLE
[schematics] Multiple imports from custom packages generated in separate lines

### ISSUE THREAD

**Issue by sooraj1002** [SamagraX-Stencil/stencil-cli#11]
## Description

Presently the cli imports one object in a single import statements even if they are from the same package. Tweak the CLI to club imports from the same package into a single import statement.

## References
**Current Behaviour:**
```typescript
import { MonitoringModule } from "@samagra-x/stencil"
import { PrometheusController } from "@samagra-x/stencil"
```

**Expected Behaviour**
```typescript
import { MonitoringModule, PrometheusController } from "@samagra-x/stencil"
```

**LoC to refer:** [monitoring module schematics](https://github.com/SamagraX-Stencil/schematics/blob/master/src/lib/monitorModule/monitorModule.factory.ts) and [monitoring generation cli](https://github.com/SamagraX-Stencil/stencil-cli/blob/master/lib/monitoring/class.monitoring.ts)

**Comment by Savio629** [comment]
> Current Behaviour:
> 
> import { MonitoringModule } from "@samagra-x/stencil"
> import { PrometheusController } from "@samagra-x/stencil"
> 
Where could I find this and How should I test this ?

// @sooraj1002 @techsavvyash

**Comment by techsavvyash** [comment]
We have linked to files where the code resides in the issue ticket itself @Savio629. As for if you want to see this in action, just bootstrap a new project with `stencil new` and add monitoring to it, you'll see this happening.
I think there are two ways to solve this:
1. Setting up the linter to club imports together -- we would want this fix applied in the `eslint` config as well.
2. Updating the schematics to generate the import statments clubbing things together. -- this is the ideal solution and needs to be a part of the PR for this issue.

**Comment by Savio629** [comment]
Am I running it properly?
There seems to be an error while running it through schematics itself
![image](https://github.com/SamagraX-Stencil/stencil-cli/assets/91362589/db262397-212e-4fb1-9af7-1c45e2780a3c)

**Comment by sooraj1002** [comment]
could you please elaborate on how you are running it through schematics itself?

to just use schematics in a project which has been bootstrapped using `@nestjs/cli`, you would need to install `@samagra-x/schematics` and then update `collection` in `nest-cli.json` to `@samagra-x/schematics` as it has been done [here](https://github.com/SamagraX-Stencil/schematics/blob/d9dd5da78af5d513fba07cb650454a9abcf1cdb1/src/lib/application/files/ts/nest-cli.json#L3).

once these changes have been  made, commands like `nest g monitormodule` should work as expected

**Comment by Savio629** [comment]
Yeah I had followed the same steps 
Is the following steps right to test it via stencil cli locally?

npm link and npm run build inside schematics
npm link and npm run build inside stencil-cli

npm link @samagra/schematics and npm link @samagra/stencil-cli inside a new project
( i also tried npm link @samagra/schematics inside of stencli-cli folder)

Now local changes should work right?

**Comment by sooraj1002** [comment]
1. `npm run build` in schematics
2. `npm link` in schematics
3. `npm link @samgra-x/schematics` in cli
4. `npm run build` in cli
5. `npm link` in cli

be sure to remove the installed `samagra-x/schematics` package from the cli before building otherwise changes in schematics wont be reflected 

now, `stencil new project` and everything else will be available globally in your system


also, could you please share a video showing the steps you followed to get that error?

**Comment by Savio629** [comment]
I have made it to work but we'll have to document it to so anyone can contribute to it easily

**Comment by Savio629** [comment]
Before:
![image](https://github.com/SamagraX-Stencil/stencil-cli/assets/91362589/fc89c520-a8eb-453b-8905-ac80f1d1a1d8)

After: 
![image](https://github.com/SamagraX-Stencil/stencil-cli/assets/91362589/4bc50d55-ad9b-4985-a978-22f1f099c648)


Ref:
Added some more modules and controllers to test
![image](https://github.com/SamagraX-Stencil/stencil-cli/assets/91362589/72b0a162-d12d-4960-806b-84820efb73d0)

**Comment by sooraj1002** [comment]
looks good. could you also remove `hello from first` being printed in the console as part of the PR for this issue?
