### ISSUE TITLE
Repeated Service-Prisma Commands

### ISSUE THREAD

**Issue by Savio629** [SamagraX-Stencil/stencil-cli#19]
## Description

when listing the commands available with stencil, `service-prisma` is repeated.

![image](https://github.com/SamagraX-Stencil/stencil-cli/assets/91362589/e31e46fe-3b4a-4adb-8bb0-ffeaca643e47)

### Expected behaviour:
Only one Service-Prisma Command should be visible

### Steps to reproduce:
Run `stencil` in the terminal

## Complexity

Low

**Comment by DarrenDsouza7273** [comment]
@techsavvyash @sooraj1002 Please check
is it possible to add C4GT tag?
