### ISSUE TITLE
[cli] gitignore is over-written

### ISSUE THREAD

**Issue by sooraj1002** [SamagraX-Stencil/stencil-cli#2]
## Description

When we setup `prisma`, the default `gitignore`  is over-written to just have `node_modules` and `.env`

This happens because we are running `npx prisma init`  for the default setup of  `prisma`  models

### Screenshots for reference

Current `.gitignore`
![image](https://github.com/SamagraX-Stencil/stencil-cli/assets/91770496/bbe35c8a-736b-4be8-9c93-53cd293f3053)

Expected `.gitignore`
![image](https://github.com/SamagraX-Stencil/stencil-cli/assets/91770496/1863399d-10ba-431d-8826-546130f3e6c7)

**Comment by Savio629** [comment]
@sooraj1002 
If we do something like this when prisma is selected?
```
cp .gitignore temp_gitignore

npx prisma init

cp temp_gitignore .gitignore

rm temp_gitignore
```

**Comment by Savio629** [comment]
// @sooraj1002 @techsavvyash

**Comment by techsavvyash** [comment]
how will this merge the changes made by `npx prisma init` in the .env?

**Comment by Savio629** [comment]
We can do the same process for .env right?

**Comment by techsavvyash** [comment]
oh sorry, nevermind, I confused between `.gitignore` and `.env`. Yes for `.gitignore` this seems to be the right approach

**Comment by Savio629** [comment]
Prisma version installed by stencil cli
prisma                  : 5.11.0
@prisma/client          : 5.11.0

This issue is fixed by prisma way back in the version 3.2.0
Ref: https://github.com/prisma/prisma/pull/8946

Any idea what's causing the issue here then?

**Comment by sooraj1002** [comment]
There is an issue in the wording of the ticket. What happens is the npx prisma init command runs before our cli is creating the gitignore and the implementation from schematics does not overwrite the created gitignore

**Comment by Savio629** [comment]
An alternative which worked is shown below

![image](https://github.com/SamagraX-Stencil/stencil-cli/assets/91362589/634fe16c-a806-43e7-9f58-37c3c20c711d)

**Comment by Savio629** [comment]
Right now when repo is initialized, there is no .gitignore so prisma treats it like no .gitignore so I'll add one
Ref: https://github.com/prisma/prisma/pull/8946
Do not create .gitignore file `if already present`

So after prisma creates a .gitignore we check if there exists .gitignore, if yes then return as shown in above code
If we don't select prisma this condition is false and we can see .gitignore file

**Comment by techsavvyash** [comment]
This approach looks good @Savio629
