### ISSUE TITLE
Merge monitor and monitoringService commands

### ISSUE THREAD

**Issue by Savio629** [SamagraX-Stencil/stencil-cli#30]
- [ ] Merge `monitor` and `monitoringService` commands in cli into one
- [ ] First level implementation on `skipDocker` command
    - [ ] for `v0.0.1` make it work with the merged monitor command to allow for opting in and out of docker setup.

**Comment by DarrenDsouza7273** [comment]
.

**Comment by sooraj1002** [comment]
- The schematics should also be updated to merge `monitorModule` and `monitor` into one command like monitoring as part of this issue

**Comment by Savio629** [comment]
Fixes/Included in pr #34
