### ISSUE TITLE
Exported class name and service name conflicting.

### ISSUE THREAD

**Issue by shivankurchavan** [SamagraX-Stencil/stencil-cli#35]
Current behavior: 
when service is generated using `stencil g service-prisma` , the cli asks for a name for that service. when given a name, it is exporting the service in form of [given service name]service format. but the file which is inside service folder is exporting `PrismaService` by default.  

Expected behavior:
Cli should not ask for naming the service.  

note: 
here in screen we can see that p1 named service was generated but PrismaService is getting exported

screenshots:

![service1](https://github.com/SamagraX-Stencil/stencil-cli/assets/61339210/65c040d4-a18f-4319-a1ca-58223e81738e)
![service2](https://github.com/SamagraX-Stencil/stencil-cli/assets/61339210/89159c92-8d4a-465e-b9fc-697d8c355dbf)

**Comment by drohan2536** [comment]
I would like to try this issue. 
@techsavvyash do we have to update the filename with the given user input and call it in the app.module.ts or we have to disable the user input and update the filename with default "Prisma.service.ts".
