### ISSUE TITLE
[cli] Aliases dont work while botstrapping a new project

### ISSUE THREAD

**Issue by sooraj1002** [SamagraX-Stencil/stencil-cli#7]
## Description

While bootstrapping a new project using, `stencil new project -ps yes` does not register the value for `prisma` as yes. similarly for all other services added, the aliases dont register, `stencil new project --prisma yes` on the other hand works fine.

**Comment by Savio629** [comment]
![image](https://github.com/SamagraX-Stencil/stencil-cli/assets/91362589/f1f748a0-2339-41d0-a0ac-803b6b8a2ce7)

Replacing `-ps` to `--ps` works !

**Comment by Savio629** [comment]
In most command line interfaces, single-dash options are typically used for single-letter options, while double-dash options are used for longer, more descriptive options.

Also `-p` won't work but different letters which are not in used works( eg. `-e`)
